### ISSUE TITLE
$watch function can't catch changes ?????

### ISSUE THREAD

**Issue by yasser-kfupm** [strongloop/loopback-example-angular-live-set#11]
Hi,

in the angular-liveset-example https://github.com/strongloop/angular-live-set-example I add $watch function to see the changes in the Live Set object "colors", however, $watch function not catching any changes !!!

any idea how to catch changes ?

Please help me

```
$scope.$watch('colors', function(newValue, oldValue) {
    console.log('update set')); 
```

**Comment by 0candy** [comment]
Does this work for you?
```
changes.on('data', function(update) {
  data.forEach(function(points) {
    if($scope.paused) return;
    points.values.push([
      update.time,
      update.usage[points.src]
    ]);

    while(points.values.length > MAX && points.values.length > 1) {
      points.values.shift();
    }

    points.values = angular.copy(points.values);
  });

  $scope.$apply();
});
```

https://github.com/strongloop/loopback-example-angular-live-set/blob/master/client/modules/chart/chart.controller.js#L36
