### ISSUE TITLE
live-set chart example gone

### ISSUE THREAD

**Issue by davidgs** [strongloop/loopback-example-angular-live-set#12]
the link for the live-set chart example at https://github.com/strongloop/angular-live-set-example/tree/feature/init/client/modules/chart has gone 404.

This would be extremely helpful in setting up live-set data from MongoDB, I think.

**Comment by 0candy** [comment]
Are you referring to this example?

https://github.com/strongloop/loopback-example-angular-live-set/tree/master/client/modules/chart

**Comment by 0candy** [comment]
I have fixed the broken links.
