### ISSUE TITLE
Mongodb persistence doesn't work when running gulp serve?

### ISSUE THREAD

**Issue by acao** [strongloop/loopback-example-angular-live-set#3]
So I wanted to experiment with performance using a persistent datasource - Mongodb.

I tried just swapping out db in server/datasources.json and installing the mongo connector, however I was given this error:

``` js
{"error":{"name":"MongoError","status":500,"message":"topology was destroyed" ..}
```

So - I did a few config changes to 'decouple' the application.
1. edited gulpfile.js to pass a full server apiUrl param to gulp-loopback-angular-sdk
2. appended the server api url to the new EventSource call in circle.controller.js
3. edited the mongo datasource config for better realtime performance
4. enabled cors

Then I ran in two console tabs - a `node .` for the server, and then a simple static server for the dist/ folder.

It worked! A bit slower than the memory datasource of course, but it was impressive.

But I can't seem to figure out why mongodb datasource isn't working with the default gulp config. Any thoughts on this?

**Comment by 0candy** [comment]
Please provide a sample repo for me to reproduce this issue:
See link: https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report
